-- =====================================================================
--  الدمرداش - قاعدة بيانات السيرفر (Supabase)
--
--  طريقة التشغيل: Supabase Dashboard ← SQL Editor ← New query
--  الصق الملف كله واضغط Run. ينفع تشغله أكتر من مرة بأمان.
--
--  Generated by tool/gen_supabase_sql.dart from lib/core/db/schema.dart.
--  Do not edit by hand: change the schema in Dart and regenerate.
-- =====================================================================

create extension if not exists pgcrypto with schema extensions;

-- Every accepted change gets the next number; phones download everything
-- newer than the last number they saw.
create sequence if not exists public.sync_seq;
grant usage, select on sequence public.sync_seq to anon, authenticated;

-- Keep the version with the newest updated_at (set by the phone). A late,
-- older version is ignored, but the stored row gets a new sequence number
-- so the phone that sent it downloads the winner.
create or replace function public.tg_sync_row() returns trigger
language plpgsql as $$
begin
  if tg_op = 'UPDATE' then
    if old.updated_at is not null and new.updated_at is not null
       and new.updated_at < old.updated_at then
      old.sync_seq := nextval('public.sync_seq');
      old.server_updated_at := clock_timestamp();
      return old;
    end if;
  end if;
  new.sync_seq := nextval('public.sync_seq');
  new.server_updated_at := clock_timestamp();
  return new;
end $$;

-- Version 1 signed people in with Supabase Auth; logins are now per
-- department (see below), so its leftovers go.
drop trigger if exists on_auth_user_created on auth.users;
drop function if exists public.handle_new_user();
drop table if exists public.profiles cascade;
-- Department logins ---------------------------------------------------------
-- One username / password per department (المعرض، التجارة) and an optional
-- owner account that sees both. Whoever signs in only types their name.
create table if not exists public.departments (
  id text primary key,
  username text not null,
  password_hash text not null,
  display_name text not null,
  division text not null,
  updated_at timestamptz not null default now()
);
create unique index if not exists departments_username_idx on public.departments (lower(username));
-- What the user is allowed to open, as a comma separated list of sections
-- (pos, stock, sales, accounts, money, reports, settings). Empty means
-- everything, which is what the first accounts of the business get.
alter table public.departments add column if not exists permissions text not null default '';
-- Somebody who left the shop: kept for the history, cannot sign in.
alter table public.departments add column if not exists active boolean not null default true;

create table if not exists public.sessions (
  token_hash text primary key,
  department_id text not null references public.departments(id) on delete cascade,
  division text not null,
  device_id uuid,
  person text,
  created_at timestamptz not null default now(),
  last_seen timestamptz not null default now()
);

create table if not exists public.login_attempts (
  username text primary key,
  failures integer not null default 0,
  locked_until timestamptz
);

-- Each phone gets a short number used as the prefix of its document numbers.
create sequence if not exists public.device_code_seq;
create table if not exists public.devices (
  id uuid primary key,
  code integer not null unique default nextval('public.device_code_seq'),
  name text,
  created_at timestamptz not null default now(),
  last_seen timestamptz not null default now()
);

-- Only reachable through the functions below.
alter table public.departments enable row level security;
alter table public.sessions enable row level security;
alter table public.login_attempts enable row level security;
alter table public.devices enable row level security;
revoke all on public.departments, public.sessions, public.login_attempts, public.devices from anon, authenticated;

create or replace function public.erp_token_hash(p_token text) returns text
language sql immutable set search_path = public, extensions as $$
  select encode(extensions.digest(coalesce(p_token, ''), 'sha256'), 'hex')
$$;

-- The phone sends its session token in the x-erp-session header.
create or replace function public.erp_current_token_hash() returns text
language sql stable set search_path = public, extensions as $$
  select public.erp_token_hash(nullif(current_setting('request.headers', true), '')::json ->> 'x-erp-session')
$$;

-- crops | appliances | all (owner) | null when not signed in.
create or replace function public.erp_session_division() returns text
language sql stable security definer set search_path = public, extensions as $$
  select s.division from public.sessions s where s.token_hash = public.erp_current_token_hash()
$$;

create or replace function public.erp_session_info() returns json
language sql stable security definer set search_path = public, extensions as $$
  select json_build_object('department', s.department_id, 'division', s.division,
                           'display_name', d.display_name, 'username', d.username)
  from public.sessions s join public.departments d on d.id = s.department_id
  where s.token_hash = public.erp_current_token_hash()
$$;

create or replace function public.erp_setup_needed() returns boolean
language sql stable security definer set search_path = public as $$
  select not exists (select 1 from public.departments)
$$;

-- First start only: create the department accounts.
create or replace function public.erp_setup(
  p_crops_user text, p_crops_pass text,
  p_app_user text, p_app_pass text,
  p_owner_user text default null, p_owner_pass text default null
) returns json
language plpgsql security definer set search_path = public, extensions as $$
begin
  lock table public.departments in exclusive mode;
  if exists (select 1 from public.departments) then
    return json_build_object('error', 'configured');
  end if;
  if coalesce(trim(p_crops_user), '') = '' or coalesce(trim(p_app_user), '') = '' then
    return json_build_object('error', 'username');
  end if;
  if lower(trim(p_crops_user)) = lower(trim(p_app_user))
     or lower(trim(coalesce(p_owner_user, ''))) in (lower(trim(p_crops_user)), lower(trim(p_app_user))) then
    return json_build_object('error', 'duplicate');
  end if;
  if coalesce(length(p_crops_pass), 0) < 6 or coalesce(length(p_app_pass), 0) < 6
     or (coalesce(trim(p_owner_user), '') <> '' and coalesce(length(p_owner_pass), 0) < 6) then
    return json_build_object('error', 'short');
  end if;
  insert into public.departments (id, username, password_hash, display_name, division) values
    ('crops', trim(p_crops_user), extensions.crypt(p_crops_pass, extensions.gen_salt('bf', 8)), 'التجارة', 'crops'),
    ('appliances', trim(p_app_user), extensions.crypt(p_app_pass, extensions.gen_salt('bf', 8)), 'المعرض', 'appliances');
  if coalesce(trim(p_owner_user), '') <> '' then
    insert into public.departments (id, username, password_hash, display_name, division) values
      ('owner', trim(p_owner_user), extensions.crypt(p_owner_pass, extensions.gen_salt('bf', 8)), 'الإدارة', 'all');
  end if;
  return json_build_object('ok', true);
end $$;

-- Errors are returned (not raised) so the failed-attempt counter is saved.
create or replace function public.erp_login(
  p_username text, p_password text, p_device uuid, p_device_name text, p_person text
) returns json
language plpgsql security definer set search_path = public, extensions as $$
declare
  v_user text := lower(trim(coalesce(p_username, '')));
  d public.departments;
  a public.login_attempts;
  v_token text;
  v_code integer;
begin
  select * into a from public.login_attempts where username = v_user;
  if a.locked_until is not null and a.locked_until > now() then
    return json_build_object('error', 'locked',
      'seconds', ceil(extract(epoch from (a.locked_until - now())))::int);
  end if;
  select * into d from public.departments where lower(username) = v_user;
  if d.id is not null and not d.active then return json_build_object('error', 'disabled'); end if;
  if d.id is null or d.password_hash <> extensions.crypt(coalesce(p_password, ''), d.password_hash) then
    insert into public.login_attempts as la (username, failures) values (v_user, 1)
    on conflict (username) do update set
      failures = case when la.locked_until is not null then 1 else la.failures + 1 end,
      locked_until = case when la.locked_until is null and la.failures + 1 >= 5
                          then now() + interval '5 minutes' end;
    return json_build_object('error', 'invalid');
  end if;
  delete from public.login_attempts where username = v_user;
  v_token := encode(extensions.gen_random_bytes(32), 'hex');
  insert into public.sessions (token_hash, department_id, division, device_id, person)
  values (public.erp_token_hash(v_token), d.id, d.division, p_device, nullif(trim(p_person), ''));
  if p_device is not null then
    update public.devices set last_seen = now(), name = coalesce(p_device_name, name)
      where id = p_device returning code into v_code;
    if v_code is null then
      insert into public.devices (id, name) values (p_device, p_device_name)
      on conflict (id) do update set last_seen = now()
      returning code into v_code;
    end if;
  end if;
  return json_build_object('token', v_token, 'department', d.id, 'division', d.division,
                           'display_name', d.display_name, 'device_code', v_code,
                           'permissions', d.permissions);
end $$;

create or replace function public.erp_logout() returns void
language sql security definer set search_path = public, extensions as $$
  delete from public.sessions where token_hash = public.erp_current_token_hash()
$$;

-- Departments the current session may manage (the owner manages all).
create or replace function public.erp_departments() returns json
language sql stable security definer set search_path = public, extensions as $$
  select coalesce(json_agg(json_build_object('id', d.id, 'username', d.username,
                                             'display_name', d.display_name,
                                             'division', d.division,
                                             'permissions', d.permissions,
                                             'active', d.active) order by d.id), '[]'::json)
  from public.departments d
  where public.erp_session_division() = 'all' or d.division = public.erp_session_division()
$$;

-- Users. Whoever is signed in to a business adds and changes the people of
-- that business; only the owner account (division 'all') touches accounts
-- that see both businesses. The permissions decide what the phone shows;
-- which business's data a user reaches is decided by his division.
create or replace function public.erp_add_user(
  p_username text, p_password text, p_name text, p_division text, p_permissions text
) returns json
language plpgsql security definer set search_path = public, extensions as $$
declare
  v_div text := public.erp_session_division();
  v_id text;
begin
  if v_div is null then return json_build_object('error', 'session'); end if;
  if v_div <> 'all' and p_division <> v_div then return json_build_object('error', 'forbidden'); end if;
  if coalesce(trim(p_username), '') = '' or coalesce(trim(p_name), '') = '' then
    return json_build_object('error', 'missing');
  end if;
  if coalesce(length(p_password), 0) < 6 then return json_build_object('error', 'short'); end if;
  if p_division not in ('crops', 'appliances', 'all') then return json_build_object('error', 'division'); end if;
  if exists (select 1 from public.departments where lower(username) = lower(trim(p_username))) then
    return json_build_object('error', 'duplicate');
  end if;
  v_id := 'u_' || encode(extensions.gen_random_bytes(8), 'hex');
  insert into public.departments (id, username, password_hash, display_name, division, permissions)
  values (v_id, trim(p_username), extensions.crypt(p_password, extensions.gen_salt('bf', 8)),
          trim(p_name), p_division, coalesce(p_permissions, ''));
  return json_build_object('ok', true, 'id', v_id);
end $$;

create or replace function public.erp_update_user(
  p_id text, p_name text, p_division text, p_permissions text, p_active boolean
) returns json
language plpgsql security definer set search_path = public, extensions as $$
declare
  v_div text := public.erp_session_division();
  d public.departments;
begin
  if v_div is null then return json_build_object('error', 'session'); end if;
  select * into d from public.departments where id = p_id;
  if d.id is null then return json_build_object('error', 'department'); end if;
  -- A business head stays inside his own business, on both sides of the change.
  if v_div <> 'all' and (d.division <> v_div or coalesce(p_division, v_div) <> v_div) then
    return json_build_object('error', 'forbidden');
  end if;
  if p_division is not null and p_division not in ('crops', 'appliances', 'all') then
    return json_build_object('error', 'division');
  end if;
  -- The business must keep at least one account that can do everything.
  if d.division = 'all'
     and (coalesce(p_active, d.active) = false or coalesce(p_division, d.division) <> 'all')
     and (select count(*) from public.departments where division = 'all' and active) <= 1 then
    return json_build_object('error', 'last_owner');
  end if;
  update public.departments set
    display_name = coalesce(nullif(trim(p_name), ''), display_name),
    division = coalesce(p_division, division),
    permissions = coalesce(p_permissions, permissions),
    active = coalesce(p_active, active),
    updated_at = now()
  where id = d.id;
  -- Whatever changed, the user signs in again and gets it.
  delete from public.sessions where department_id = d.id;
  return json_build_object('ok', true);
end $$;

create or replace function public.erp_delete_user(p_id text) returns json
language plpgsql security definer set search_path = public, extensions as $$
declare
  v_div text := public.erp_session_division();
  d public.departments;
begin
  if v_div is null then return json_build_object('error', 'session'); end if;
  select * into d from public.departments where id = p_id;
  if d.id is null then return json_build_object('error', 'department'); end if;
  if v_div <> 'all' and d.division <> v_div then return json_build_object('error', 'forbidden'); end if;
  if exists (select 1 from public.sessions
             where token_hash = public.erp_current_token_hash() and department_id = d.id) then
    return json_build_object('error', 'self');
  end if;
  if d.division = 'all'
     and (select count(*) from public.departments where division = 'all' and active) <= 1 then
    return json_build_object('error', 'last_owner');
  end if;
  delete from public.departments where id = d.id;
  return json_build_object('ok', true);
end $$;

-- Change a department's username / password. Everybody else signed in to
-- that department has to sign in again.
create or replace function public.erp_change_password(
  p_department text, p_old text, p_new text, p_new_username text default null
) returns json
language plpgsql security definer set search_path = public, extensions as $$
declare
  v_div text := public.erp_session_division();
  v_hash text := public.erp_current_token_hash();
  d public.departments;
begin
  if v_div is null then return json_build_object('error', 'session'); end if;
  select * into d from public.departments where id = p_department;
  if d.id is null then return json_build_object('error', 'department'); end if;
  if v_div <> 'all' and v_div <> d.division then return json_build_object('error', 'forbidden'); end if;
  if v_div <> 'all' and d.password_hash <> extensions.crypt(coalesce(p_old, ''), d.password_hash) then
    return json_build_object('error', 'old_password');
  end if;
  if coalesce(length(p_new), 0) < 6 then return json_build_object('error', 'short'); end if;
  if coalesce(trim(p_new_username), '') <> '' and exists (
       select 1 from public.departments where lower(username) = lower(trim(p_new_username)) and id <> d.id) then
    return json_build_object('error', 'duplicate');
  end if;
  update public.departments set
    password_hash = extensions.crypt(p_new, extensions.gen_salt('bf', 8)),
    username = coalesce(nullif(trim(p_new_username), ''), username),
    updated_at = now()
  where id = d.id;
  delete from public.sessions where department_id = d.id and token_hash <> v_hash;
  return json_build_object('ok', true);
end $$;

create or replace function public.server_now() returns timestamptz
language sql volatile as $$ select clock_timestamp() $$;

-- Changes every time supabase/reset_data.sql wipes the data; phones compare it
-- before uploading, so an old copy is never sent back to a wiped server.
create table if not exists public.erp_state (
  id integer primary key default 1 check (id = 1),
  reset_id text not null default gen_random_uuid()::text,
  reset_at timestamptz not null default now()
);
insert into public.erp_state (id) values (1) on conflict (id) do nothing;
alter table public.erp_state enable row level security;
revoke all on public.erp_state from anon, authenticated;

create or replace function public.erp_reset_id() returns text
language sql stable security definer set search_path = public as $$
  select reset_id from public.erp_state where id = 1
$$;

grant execute on function public.erp_token_hash(text) to anon, authenticated;
grant execute on function public.erp_current_token_hash() to anon, authenticated;
grant execute on function public.erp_session_division() to anon, authenticated;
grant execute on function public.erp_session_info() to anon, authenticated;
grant execute on function public.erp_setup_needed() to anon, authenticated;
grant execute on function public.erp_setup(text, text, text, text, text, text) to anon, authenticated;
grant execute on function public.erp_login(text, text, uuid, text, text) to anon, authenticated;
grant execute on function public.erp_add_user(text, text, text, text, text) to anon, authenticated;
grant execute on function public.erp_update_user(text, text, text, text, boolean) to anon, authenticated;
grant execute on function public.erp_delete_user(text) to anon, authenticated;
grant execute on function public.erp_logout() to anon, authenticated;
grant execute on function public.erp_departments() to anon, authenticated;
grant execute on function public.erp_change_password(text, text, text, text) to anon, authenticated;
grant execute on function public.server_now() to anon, authenticated;
grant execute on function public.erp_reset_id() to anon, authenticated;

-- app_settings ----------------------------------------------------------
create table if not exists public.app_settings (
  id text primary key,
  sync_seq bigint not null default 0,
  server_updated_at timestamptz not null default now()
);
alter table public.app_settings add column if not exists division text not null default 'crops';
alter table public.app_settings add column if not exists value text;
alter table public.app_settings add column if not exists created_at timestamptz;
alter table public.app_settings add column if not exists updated_at timestamptz;
alter table public.app_settings add column if not exists deleted boolean not null default false;
alter table public.app_settings add column if not exists created_by_name text;
alter table public.app_settings add column if not exists updated_by_name text;
create index if not exists app_settings_sync_seq_idx on public.app_settings (sync_seq);
create index if not exists app_settings_division_idx on public.app_settings (division, sync_seq);
drop trigger if exists app_settings_sync on public.app_settings;
create trigger app_settings_sync before insert or update on public.app_settings for each row execute function public.tg_sync_row();
alter table public.app_settings enable row level security;
grant select, insert, update on public.app_settings to anon, authenticated;
drop policy if exists app_settings_select on public.app_settings;
create policy app_settings_select on public.app_settings for select to anon, authenticated using ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null));
drop policy if exists app_settings_insert on public.app_settings;
create policy app_settings_insert on public.app_settings for insert to anon, authenticated with check ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null));
drop policy if exists app_settings_update on public.app_settings;
create policy app_settings_update on public.app_settings for update to anon, authenticated using ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null)) with check ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null));

-- parties ---------------------------------------------------------------
create table if not exists public.parties (
  id uuid primary key,
  sync_seq bigint not null default 0,
  server_updated_at timestamptz not null default now()
);
alter table public.parties add column if not exists division text not null default 'crops';
alter table public.parties add column if not exists name text not null default '';
alter table public.parties add column if not exists kind text not null default 'customer';
alter table public.parties add column if not exists phone text;
alter table public.parties add column if not exists address text;
alter table public.parties add column if not exists national_id text;
alter table public.parties add column if not exists opening_balance numeric not null default 0;
alter table public.parties add column if not exists collect_on date;
alter table public.parties add column if not exists credit_limit numeric not null default 0;
alter table public.parties add column if not exists notes text;
alter table public.parties add column if not exists created_at timestamptz;
alter table public.parties add column if not exists updated_at timestamptz;
alter table public.parties add column if not exists deleted boolean not null default false;
alter table public.parties add column if not exists created_by_name text;
alter table public.parties add column if not exists updated_by_name text;
create index if not exists parties_sync_seq_idx on public.parties (sync_seq);
create index if not exists parties_division_idx on public.parties (division, sync_seq);
drop trigger if exists parties_sync on public.parties;
create trigger parties_sync before insert or update on public.parties for each row execute function public.tg_sync_row();
alter table public.parties enable row level security;
grant select, insert, update on public.parties to anon, authenticated;
drop policy if exists parties_select on public.parties;
create policy parties_select on public.parties for select to anon, authenticated using ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null));
drop policy if exists parties_insert on public.parties;
create policy parties_insert on public.parties for insert to anon, authenticated with check ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null));
drop policy if exists parties_update on public.parties;
create policy parties_update on public.parties for update to anon, authenticated using ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null)) with check ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null));

-- warehouses ------------------------------------------------------------
create table if not exists public.warehouses (
  id uuid primary key,
  sync_seq bigint not null default 0,
  server_updated_at timestamptz not null default now()
);
alter table public.warehouses add column if not exists division text not null default 'crops';
alter table public.warehouses add column if not exists name text not null default '';
alter table public.warehouses add column if not exists notes text;
alter table public.warehouses add column if not exists active boolean not null default true;
alter table public.warehouses add column if not exists created_at timestamptz;
alter table public.warehouses add column if not exists updated_at timestamptz;
alter table public.warehouses add column if not exists deleted boolean not null default false;
alter table public.warehouses add column if not exists created_by_name text;
alter table public.warehouses add column if not exists updated_by_name text;
create index if not exists warehouses_sync_seq_idx on public.warehouses (sync_seq);
create index if not exists warehouses_division_idx on public.warehouses (division, sync_seq);
drop trigger if exists warehouses_sync on public.warehouses;
create trigger warehouses_sync before insert or update on public.warehouses for each row execute function public.tg_sync_row();
alter table public.warehouses enable row level security;
grant select, insert, update on public.warehouses to anon, authenticated;
drop policy if exists warehouses_select on public.warehouses;
create policy warehouses_select on public.warehouses for select to anon, authenticated using ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null));
drop policy if exists warehouses_insert on public.warehouses;
create policy warehouses_insert on public.warehouses for insert to anon, authenticated with check ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null));
drop policy if exists warehouses_update on public.warehouses;
create policy warehouses_update on public.warehouses for update to anon, authenticated using ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null)) with check ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null));

-- cash_boxes ------------------------------------------------------------
create table if not exists public.cash_boxes (
  id uuid primary key,
  sync_seq bigint not null default 0,
  server_updated_at timestamptz not null default now()
);
alter table public.cash_boxes add column if not exists division text not null default 'crops';
alter table public.cash_boxes add column if not exists name text not null default '';
alter table public.cash_boxes add column if not exists opening_balance numeric not null default 0;
alter table public.cash_boxes add column if not exists notes text;
alter table public.cash_boxes add column if not exists active boolean not null default true;
alter table public.cash_boxes add column if not exists created_at timestamptz;
alter table public.cash_boxes add column if not exists updated_at timestamptz;
alter table public.cash_boxes add column if not exists deleted boolean not null default false;
alter table public.cash_boxes add column if not exists created_by_name text;
alter table public.cash_boxes add column if not exists updated_by_name text;
create index if not exists cash_boxes_sync_seq_idx on public.cash_boxes (sync_seq);
create index if not exists cash_boxes_division_idx on public.cash_boxes (division, sync_seq);
drop trigger if exists cash_boxes_sync on public.cash_boxes;
create trigger cash_boxes_sync before insert or update on public.cash_boxes for each row execute function public.tg_sync_row();
alter table public.cash_boxes enable row level security;
grant select, insert, update on public.cash_boxes to anon, authenticated;
drop policy if exists cash_boxes_select on public.cash_boxes;
create policy cash_boxes_select on public.cash_boxes for select to anon, authenticated using ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null));
drop policy if exists cash_boxes_insert on public.cash_boxes;
create policy cash_boxes_insert on public.cash_boxes for insert to anon, authenticated with check ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null));
drop policy if exists cash_boxes_update on public.cash_boxes;
create policy cash_boxes_update on public.cash_boxes for update to anon, authenticated using ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null)) with check ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null));

-- crops -----------------------------------------------------------------
create table if not exists public.crops (
  id uuid primary key,
  sync_seq bigint not null default 0,
  server_updated_at timestamptz not null default now()
);
alter table public.crops add column if not exists division text not null default 'crops';
alter table public.crops add column if not exists name text not null default '';
alter table public.crops add column if not exists unit_name text not null default 'طن';
alter table public.crops add column if not exists kg_per_unit numeric not null default 1000;
alter table public.crops add column if not exists buy_price numeric not null default 0;
alter table public.crops add column if not exists sell_price numeric not null default 0;
alter table public.crops add column if not exists notes text;
alter table public.crops add column if not exists active boolean not null default true;
alter table public.crops add column if not exists created_at timestamptz;
alter table public.crops add column if not exists updated_at timestamptz;
alter table public.crops add column if not exists deleted boolean not null default false;
alter table public.crops add column if not exists created_by_name text;
alter table public.crops add column if not exists updated_by_name text;
create index if not exists crops_sync_seq_idx on public.crops (sync_seq);
create index if not exists crops_division_idx on public.crops (division, sync_seq);
drop trigger if exists crops_sync on public.crops;
create trigger crops_sync before insert or update on public.crops for each row execute function public.tg_sync_row();
alter table public.crops enable row level security;
grant select, insert, update on public.crops to anon, authenticated;
drop policy if exists crops_select on public.crops;
create policy crops_select on public.crops for select to anon, authenticated using ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null));
drop policy if exists crops_insert on public.crops;
create policy crops_insert on public.crops for insert to anon, authenticated with check ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null));
drop policy if exists crops_update on public.crops;
create policy crops_update on public.crops for update to anon, authenticated using ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null)) with check ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null));

-- products --------------------------------------------------------------
create table if not exists public.products (
  id uuid primary key,
  sync_seq bigint not null default 0,
  server_updated_at timestamptz not null default now()
);
alter table public.products add column if not exists division text not null default 'appliances';
alter table public.products add column if not exists name text not null default '';
alter table public.products add column if not exists category text;
alter table public.products add column if not exists brand text;
alter table public.products add column if not exists model text;
alter table public.products add column if not exists barcode text;
alter table public.products add column if not exists unit text not null default 'قطعة';
alter table public.products add column if not exists cost_price numeric not null default 0;
alter table public.products add column if not exists retail_price numeric not null default 0;
alter table public.products add column if not exists wholesale_price numeric not null default 0;
alter table public.products add column if not exists min_qty numeric not null default 0;
alter table public.products add column if not exists notes text;
alter table public.products add column if not exists active boolean not null default true;
alter table public.products add column if not exists created_at timestamptz;
alter table public.products add column if not exists updated_at timestamptz;
alter table public.products add column if not exists deleted boolean not null default false;
alter table public.products add column if not exists created_by_name text;
alter table public.products add column if not exists updated_by_name text;
create index if not exists products_sync_seq_idx on public.products (sync_seq);
create index if not exists products_division_idx on public.products (division, sync_seq);
drop trigger if exists products_sync on public.products;
create trigger products_sync before insert or update on public.products for each row execute function public.tg_sync_row();
alter table public.products enable row level security;
grant select, insert, update on public.products to anon, authenticated;
drop policy if exists products_select on public.products;
create policy products_select on public.products for select to anon, authenticated using ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null));
drop policy if exists products_insert on public.products;
create policy products_insert on public.products for insert to anon, authenticated with check ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null));
drop policy if exists products_update on public.products;
create policy products_update on public.products for update to anon, authenticated using ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null)) with check ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null));

-- crop_trades -----------------------------------------------------------
create table if not exists public.crop_trades (
  id uuid primary key,
  sync_seq bigint not null default 0,
  server_updated_at timestamptz not null default now()
);
alter table public.crop_trades add column if not exists division text not null default 'crops';
alter table public.crop_trades add column if not exists kind text not null default 'purchase';
alter table public.crop_trades add column if not exists number text;
alter table public.crop_trades add column if not exists date date;
alter table public.crop_trades add column if not exists party_id uuid;
alter table public.crop_trades add column if not exists crop_id uuid;
alter table public.crop_trades add column if not exists warehouse_id uuid;
alter table public.crop_trades add column if not exists cash_box_id uuid;
alter table public.crop_trades add column if not exists unit_name text;
alter table public.crop_trades add column if not exists kg_per_unit numeric not null default 1000;
alter table public.crop_trades add column if not exists weigh_mode text not null default 'scale';
alter table public.crop_trades add column if not exists gross_kg numeric not null default 0;
alter table public.crop_trades add column if not exists tare_kg numeric not null default 0;
alter table public.crop_trades add column if not exists sack_weights text;
alter table public.crop_trades add column if not exists bags_count numeric not null default 0;
alter table public.crop_trades add column if not exists bag_weight_kg numeric not null default 0;
alter table public.crop_trades add column if not exists moisture_kg numeric not null default 0;
alter table public.crop_trades add column if not exists impurities_kg numeric not null default 0;
alter table public.crop_trades add column if not exists moisture_pct numeric not null default 0;
alter table public.crop_trades add column if not exists impurities_pct numeric not null default 0;
alter table public.crop_trades add column if not exists other_deduction_kg numeric not null default 0;
alter table public.crop_trades add column if not exists net_kg numeric not null default 0;
alter table public.crop_trades add column if not exists stock_kg numeric not null default 0;
alter table public.crop_trades add column if not exists price_per_unit numeric not null default 0;
alter table public.crop_trades add column if not exists subtotal numeric not null default 0;
alter table public.crop_trades add column if not exists freight numeric not null default 0;
alter table public.crop_trades add column if not exists loading numeric not null default 0;
alter table public.crop_trades add column if not exists other_expenses numeric not null default 0;
alter table public.crop_trades add column if not exists expenses_on_party boolean not null default false;
alter table public.crop_trades add column if not exists party_total numeric not null default 0;
alter table public.crop_trades add column if not exists paid_amount numeric not null default 0;
alter table public.crop_trades add column if not exists ticket_no text;
alter table public.crop_trades add column if not exists vehicle text;
alter table public.crop_trades add column if not exists notes text;
alter table public.crop_trades add column if not exists created_at timestamptz;
alter table public.crop_trades add column if not exists updated_at timestamptz;
alter table public.crop_trades add column if not exists deleted boolean not null default false;
alter table public.crop_trades add column if not exists created_by_name text;
alter table public.crop_trades add column if not exists updated_by_name text;
create index if not exists crop_trades_sync_seq_idx on public.crop_trades (sync_seq);
create index if not exists crop_trades_division_idx on public.crop_trades (division, sync_seq);
drop trigger if exists crop_trades_sync on public.crop_trades;
create trigger crop_trades_sync before insert or update on public.crop_trades for each row execute function public.tg_sync_row();
alter table public.crop_trades enable row level security;
grant select, insert, update on public.crop_trades to anon, authenticated;
drop policy if exists crop_trades_select on public.crop_trades;
create policy crop_trades_select on public.crop_trades for select to anon, authenticated using ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null));
drop policy if exists crop_trades_insert on public.crop_trades;
create policy crop_trades_insert on public.crop_trades for insert to anon, authenticated with check ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null));
drop policy if exists crop_trades_update on public.crop_trades;
create policy crop_trades_update on public.crop_trades for update to anon, authenticated using ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null)) with check ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null));

-- invoices --------------------------------------------------------------
create table if not exists public.invoices (
  id uuid primary key,
  sync_seq bigint not null default 0,
  server_updated_at timestamptz not null default now()
);
alter table public.invoices add column if not exists division text not null default 'appliances';
alter table public.invoices add column if not exists kind text not null default 'sale';
alter table public.invoices add column if not exists number text;
alter table public.invoices add column if not exists date date;
alter table public.invoices add column if not exists party_id uuid;
alter table public.invoices add column if not exists customer_name text;
alter table public.invoices add column if not exists warehouse_id uuid;
alter table public.invoices add column if not exists cash_box_id uuid;
alter table public.invoices add column if not exists price_level text not null default 'retail';
alter table public.invoices add column if not exists payment_type text not null default 'cash';
alter table public.invoices add column if not exists subtotal numeric not null default 0;
alter table public.invoices add column if not exists discount numeric not null default 0;
alter table public.invoices add column if not exists total numeric not null default 0;
alter table public.invoices add column if not exists markup_pct numeric not null default 0;
alter table public.invoices add column if not exists markup_amount numeric not null default 0;
alter table public.invoices add column if not exists grand_total numeric not null default 0;
alter table public.invoices add column if not exists paid_amount numeric not null default 0;
alter table public.invoices add column if not exists inst_months integer not null default 0;
alter table public.invoices add column if not exists inst_first_due date;
alter table public.invoices add column if not exists guarantor_name text;
alter table public.invoices add column if not exists guarantor_phone text;
alter table public.invoices add column if not exists ref_invoice_id uuid;
alter table public.invoices add column if not exists source text not null default 'form';
alter table public.invoices add column if not exists rev text;
alter table public.invoices add column if not exists notes text;
alter table public.invoices add column if not exists created_at timestamptz;
alter table public.invoices add column if not exists updated_at timestamptz;
alter table public.invoices add column if not exists deleted boolean not null default false;
alter table public.invoices add column if not exists created_by_name text;
alter table public.invoices add column if not exists updated_by_name text;
create index if not exists invoices_sync_seq_idx on public.invoices (sync_seq);
create index if not exists invoices_division_idx on public.invoices (division, sync_seq);
drop trigger if exists invoices_sync on public.invoices;
create trigger invoices_sync before insert or update on public.invoices for each row execute function public.tg_sync_row();
alter table public.invoices enable row level security;
grant select, insert, update on public.invoices to anon, authenticated;
drop policy if exists invoices_select on public.invoices;
create policy invoices_select on public.invoices for select to anon, authenticated using ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null));
drop policy if exists invoices_insert on public.invoices;
create policy invoices_insert on public.invoices for insert to anon, authenticated with check ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null));
drop policy if exists invoices_update on public.invoices;
create policy invoices_update on public.invoices for update to anon, authenticated using ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null)) with check ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null));

-- invoice_lines ---------------------------------------------------------
create table if not exists public.invoice_lines (
  id uuid primary key,
  sync_seq bigint not null default 0,
  server_updated_at timestamptz not null default now()
);
alter table public.invoice_lines add column if not exists division text not null default 'appliances';
alter table public.invoice_lines add column if not exists invoice_id uuid;
alter table public.invoice_lines add column if not exists rev text;
alter table public.invoice_lines add column if not exists sort integer not null default 0;
alter table public.invoice_lines add column if not exists product_id uuid;
alter table public.invoice_lines add column if not exists qty numeric not null default 0;
alter table public.invoice_lines add column if not exists price numeric not null default 0;
alter table public.invoice_lines add column if not exists total numeric not null default 0;
alter table public.invoice_lines add column if not exists notes text;
alter table public.invoice_lines add column if not exists created_at timestamptz;
alter table public.invoice_lines add column if not exists updated_at timestamptz;
alter table public.invoice_lines add column if not exists deleted boolean not null default false;
alter table public.invoice_lines add column if not exists created_by_name text;
alter table public.invoice_lines add column if not exists updated_by_name text;
create index if not exists invoice_lines_sync_seq_idx on public.invoice_lines (sync_seq);
create index if not exists invoice_lines_division_idx on public.invoice_lines (division, sync_seq);
drop trigger if exists invoice_lines_sync on public.invoice_lines;
create trigger invoice_lines_sync before insert or update on public.invoice_lines for each row execute function public.tg_sync_row();
alter table public.invoice_lines enable row level security;
grant select, insert, update on public.invoice_lines to anon, authenticated;
drop policy if exists invoice_lines_select on public.invoice_lines;
create policy invoice_lines_select on public.invoice_lines for select to anon, authenticated using ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null));
drop policy if exists invoice_lines_insert on public.invoice_lines;
create policy invoice_lines_insert on public.invoice_lines for insert to anon, authenticated with check ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null));
drop policy if exists invoice_lines_update on public.invoice_lines;
create policy invoice_lines_update on public.invoice_lines for update to anon, authenticated using ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null)) with check ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null));

-- installments ----------------------------------------------------------
create table if not exists public.installments (
  id uuid primary key,
  sync_seq bigint not null default 0,
  server_updated_at timestamptz not null default now()
);
alter table public.installments add column if not exists division text not null default 'appliances';
alter table public.installments add column if not exists invoice_id uuid;
alter table public.installments add column if not exists rev text;
alter table public.installments add column if not exists party_id uuid;
alter table public.installments add column if not exists seq integer not null default 0;
alter table public.installments add column if not exists due_date date;
alter table public.installments add column if not exists amount numeric not null default 0;
alter table public.installments add column if not exists created_at timestamptz;
alter table public.installments add column if not exists updated_at timestamptz;
alter table public.installments add column if not exists deleted boolean not null default false;
alter table public.installments add column if not exists created_by_name text;
alter table public.installments add column if not exists updated_by_name text;
create index if not exists installments_sync_seq_idx on public.installments (sync_seq);
create index if not exists installments_division_idx on public.installments (division, sync_seq);
drop trigger if exists installments_sync on public.installments;
create trigger installments_sync before insert or update on public.installments for each row execute function public.tg_sync_row();
alter table public.installments enable row level security;
grant select, insert, update on public.installments to anon, authenticated;
drop policy if exists installments_select on public.installments;
create policy installments_select on public.installments for select to anon, authenticated using ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null));
drop policy if exists installments_insert on public.installments;
create policy installments_insert on public.installments for insert to anon, authenticated with check ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null));
drop policy if exists installments_update on public.installments;
create policy installments_update on public.installments for update to anon, authenticated using ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null)) with check ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null));

-- vouchers --------------------------------------------------------------
create table if not exists public.vouchers (
  id uuid primary key,
  sync_seq bigint not null default 0,
  server_updated_at timestamptz not null default now()
);
alter table public.vouchers add column if not exists division text not null default 'crops';
alter table public.vouchers add column if not exists kind text not null default 'receipt';
alter table public.vouchers add column if not exists number text;
alter table public.vouchers add column if not exists date date;
alter table public.vouchers add column if not exists party_id uuid;
alter table public.vouchers add column if not exists cash_box_id uuid;
alter table public.vouchers add column if not exists to_cash_box_id uuid;
alter table public.vouchers add column if not exists amount numeric not null default 0;
alter table public.vouchers add column if not exists category text;
alter table public.vouchers add column if not exists invoice_id uuid;
alter table public.vouchers add column if not exists handled_by text;
alter table public.vouchers add column if not exists notes text;
alter table public.vouchers add column if not exists created_at timestamptz;
alter table public.vouchers add column if not exists updated_at timestamptz;
alter table public.vouchers add column if not exists deleted boolean not null default false;
alter table public.vouchers add column if not exists created_by_name text;
alter table public.vouchers add column if not exists updated_by_name text;
create index if not exists vouchers_sync_seq_idx on public.vouchers (sync_seq);
create index if not exists vouchers_division_idx on public.vouchers (division, sync_seq);
drop trigger if exists vouchers_sync on public.vouchers;
create trigger vouchers_sync before insert or update on public.vouchers for each row execute function public.tg_sync_row();
alter table public.vouchers enable row level security;
grant select, insert, update on public.vouchers to anon, authenticated;
drop policy if exists vouchers_select on public.vouchers;
create policy vouchers_select on public.vouchers for select to anon, authenticated using ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null));
drop policy if exists vouchers_insert on public.vouchers;
create policy vouchers_insert on public.vouchers for insert to anon, authenticated with check ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null));
drop policy if exists vouchers_update on public.vouchers;
create policy vouchers_update on public.vouchers for update to anon, authenticated using ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null)) with check ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null));

-- stock_moves -----------------------------------------------------------
create table if not exists public.stock_moves (
  id uuid primary key,
  sync_seq bigint not null default 0,
  server_updated_at timestamptz not null default now()
);
alter table public.stock_moves add column if not exists division text not null default 'crops';
alter table public.stock_moves add column if not exists kind text not null default 'adjust';
alter table public.stock_moves add column if not exists number text;
alter table public.stock_moves add column if not exists date date;
alter table public.stock_moves add column if not exists item_type text not null default 'crop';
alter table public.stock_moves add column if not exists item_id uuid;
alter table public.stock_moves add column if not exists warehouse_id uuid;
alter table public.stock_moves add column if not exists to_warehouse_id uuid;
alter table public.stock_moves add column if not exists qty numeric not null default 0;
alter table public.stock_moves add column if not exists notes text;
alter table public.stock_moves add column if not exists created_at timestamptz;
alter table public.stock_moves add column if not exists updated_at timestamptz;
alter table public.stock_moves add column if not exists deleted boolean not null default false;
alter table public.stock_moves add column if not exists created_by_name text;
alter table public.stock_moves add column if not exists updated_by_name text;
create index if not exists stock_moves_sync_seq_idx on public.stock_moves (sync_seq);
create index if not exists stock_moves_division_idx on public.stock_moves (division, sync_seq);
drop trigger if exists stock_moves_sync on public.stock_moves;
create trigger stock_moves_sync before insert or update on public.stock_moves for each row execute function public.tg_sync_row();
alter table public.stock_moves enable row level security;
grant select, insert, update on public.stock_moves to anon, authenticated;
drop policy if exists stock_moves_select on public.stock_moves;
create policy stock_moves_select on public.stock_moves for select to anon, authenticated using ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null));
drop policy if exists stock_moves_insert on public.stock_moves;
create policy stock_moves_insert on public.stock_moves for insert to anon, authenticated with check ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null));
drop policy if exists stock_moves_update on public.stock_moves;
create policy stock_moves_update on public.stock_moves for update to anon, authenticated using ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null)) with check ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null));

-- notes -----------------------------------------------------------------
create table if not exists public.notes (
  id uuid primary key,
  sync_seq bigint not null default 0,
  server_updated_at timestamptz not null default now()
);
alter table public.notes add column if not exists division text not null default 'crops';
alter table public.notes add column if not exists kind text not null default 'note';
alter table public.notes add column if not exists body text not null default '';
alter table public.notes add column if not exists amount numeric not null default 0;
alter table public.notes add column if not exists person text;
alter table public.notes add column if not exists due_date date;
alter table public.notes add column if not exists done boolean not null default false;
alter table public.notes add column if not exists done_by text;
alter table public.notes add column if not exists done_at timestamptz;
alter table public.notes add column if not exists pinned boolean not null default false;
alter table public.notes add column if not exists created_at timestamptz;
alter table public.notes add column if not exists updated_at timestamptz;
alter table public.notes add column if not exists deleted boolean not null default false;
alter table public.notes add column if not exists created_by_name text;
alter table public.notes add column if not exists updated_by_name text;
create index if not exists notes_sync_seq_idx on public.notes (sync_seq);
create index if not exists notes_division_idx on public.notes (division, sync_seq);
drop trigger if exists notes_sync on public.notes;
create trigger notes_sync before insert or update on public.notes for each row execute function public.tg_sync_row();
alter table public.notes enable row level security;
grant select, insert, update on public.notes to anon, authenticated;
drop policy if exists notes_select on public.notes;
create policy notes_select on public.notes for select to anon, authenticated using ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null));
drop policy if exists notes_insert on public.notes;
create policy notes_insert on public.notes for insert to anon, authenticated with check ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null));
drop policy if exists notes_update on public.notes;
create policy notes_update on public.notes for update to anon, authenticated using ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null)) with check ((select public.erp_session_division()) = 'all' or division = (select public.erp_session_division()) or (division = 'all' and (select public.erp_session_division()) is not null));

-- Version 1 functions, no longer referenced by any policy.
drop function if exists public.register_device(uuid, text);
drop function if exists public.is_active_member();
drop function if exists public.is_admin();

