// Generates supabase/schema.sql from lib/core/db/schema.dart.
//
//   dart run tool/gen_supabase_sql.dart
//
// The script is idempotent: running it again on an existing project adds new
// columns and refreshes functions, triggers and policies without losing data.
// It also upgrades projects that ran the first version (Supabase Auth based).
import 'dart:io';

import 'package:trade_erp/core/db/schema.dart';

String pgType(ColType t) => switch (t) {
      ColType.text => 'text',
      ColType.real => 'numeric',
      ColType.integer => 'integer',
      ColType.boolean => 'boolean',
      ColType.date => 'date',
      ColType.timestamp => 'timestamptz',
      ColType.uuid => 'uuid',
    };

String pgLiteral(Object d) {
  if (d is bool) return d ? 'true' : 'false';
  if (d is num) return '$d';
  return "'${d.toString().replaceAll("'", "''")}'";
}

String columnDef(Col c) {
  final base = '${c.name} ${pgType(c.type)}';
  return c.def == null ? base : '$base not null default ${pgLiteral(c.def!)}';
}

/// Rows are visible to the session's division, to the owner account and,
/// for rows marked 'all' (shared notes), to everybody signed in.
const _access = "((select public.erp_session_division()) = 'all' "
    'or division = (select public.erp_session_division()) '
    "or (division = 'all' and (select public.erp_session_division()) is not null))";

String tableSql(TableDef t) {
  final b = StringBuffer();
  final n = t.name;
  final idType = t.textId ? 'text' : 'uuid';
  b.writeln('-- $n ${'-' * (70 - n.length)}');
  b.writeln('create table if not exists public.$n (');
  b.writeln('  id $idType primary key,');
  b.writeln('  sync_seq bigint not null default 0,');
  b.writeln('  server_updated_at timestamptz not null default now()');
  b.writeln(');');
  for (final c in t.allCols.where((c) => c.name != 'id')) {
    b.writeln('alter table public.$n add column if not exists ${columnDef(c)};');
  }
  b.writeln('create index if not exists ${n}_sync_seq_idx on public.$n (sync_seq);');
  b.writeln('create index if not exists ${n}_division_idx on public.$n (division, sync_seq);');
  b.writeln('drop trigger if exists ${n}_sync on public.$n;');
  b.writeln('create trigger ${n}_sync before insert or update on public.$n '
      'for each row execute function public.tg_sync_row();');
  b.writeln('alter table public.$n enable row level security;');
  b.writeln('grant select, insert, update on public.$n to anon, authenticated;');
  b.writeln('drop policy if exists ${n}_select on public.$n;');
  b.writeln('create policy ${n}_select on public.$n for select to anon, authenticated using $_access;');
  b.writeln('drop policy if exists ${n}_insert on public.$n;');
  b.writeln('create policy ${n}_insert on public.$n for insert to anon, authenticated with check $_access;');
  b.writeln('drop policy if exists ${n}_update on public.$n;');
  b.writeln('create policy ${n}_update on public.$n for update to anon, authenticated '
      'using $_access with check $_access;');
  return b.toString();
}

const header = r'''
-- =====================================================================
--  الدمرداش - قاعدة بيانات السيرفر (Supabase)
--
--  طريقة التشغيل: Supabase Dashboard ← SQL Editor ← New query
--  الصق الملف كله واضغط Run. ينفع تشغله أكتر من مرة بأمان.
--
--  Generated by tool/gen_supabase_sql.dart from lib/core/db/schema.dart.
--  Do not edit by hand: change the schema in Dart and regenerate.
-- =====================================================================

create extension if not exists pgcrypto with schema extensions;

-- Every accepted change gets the next number; phones download everything
-- newer than the last number they saw.
create sequence if not exists public.sync_seq;
grant usage, select on sequence public.sync_seq to anon, authenticated;

-- Keep the version with the newest updated_at (set by the phone). A late,
-- older version is ignored, but the stored row gets a new sequence number
-- so the phone that sent it downloads the winner.
create or replace function public.tg_sync_row() returns trigger
language plpgsql as $$
begin
  if tg_op = 'UPDATE' then
    if old.updated_at is not null and new.updated_at is not null
       and new.updated_at < old.updated_at then
      old.sync_seq := nextval('public.sync_seq');
      old.server_updated_at := clock_timestamp();
      return old;
    end if;
  end if;
  new.sync_seq := nextval('public.sync_seq');
  new.server_updated_at := clock_timestamp();
  return new;
end $$;

-- Version 1 signed people in with Supabase Auth; logins are now per
-- department (see below), so its leftovers go.
drop trigger if exists on_auth_user_created on auth.users;
drop function if exists public.handle_new_user();
drop table if exists public.profiles cascade;
''';

const accessSql = r'''
-- Department logins ---------------------------------------------------------
-- One username / password per department (المعرض، التجارة) and an optional
-- owner account that sees both. Whoever signs in only types their name.
create table if not exists public.departments (
  id text primary key,
  username text not null,
  password_hash text not null,
  display_name text not null,
  division text not null,
  updated_at timestamptz not null default now()
);
create unique index if not exists departments_username_idx on public.departments (lower(username));

create table if not exists public.sessions (
  token_hash text primary key,
  department_id text not null references public.departments(id) on delete cascade,
  division text not null,
  device_id uuid,
  person text,
  created_at timestamptz not null default now(),
  last_seen timestamptz not null default now()
);

create table if not exists public.login_attempts (
  username text primary key,
  failures integer not null default 0,
  locked_until timestamptz
);

-- Each phone gets a short number used as the prefix of its document numbers.
create sequence if not exists public.device_code_seq;
create table if not exists public.devices (
  id uuid primary key,
  code integer not null unique default nextval('public.device_code_seq'),
  name text,
  created_at timestamptz not null default now(),
  last_seen timestamptz not null default now()
);

-- Only reachable through the functions below.
alter table public.departments enable row level security;
alter table public.sessions enable row level security;
alter table public.login_attempts enable row level security;
alter table public.devices enable row level security;
revoke all on public.departments, public.sessions, public.login_attempts, public.devices from anon, authenticated;

create or replace function public.erp_token_hash(p_token text) returns text
language sql immutable set search_path = public, extensions as $$
  select encode(extensions.digest(coalesce(p_token, ''), 'sha256'), 'hex')
$$;

-- The phone sends its session token in the x-erp-session header.
create or replace function public.erp_current_token_hash() returns text
language sql stable set search_path = public, extensions as $$
  select public.erp_token_hash(nullif(current_setting('request.headers', true), '')::json ->> 'x-erp-session')
$$;

-- crops | appliances | all (owner) | null when not signed in.
create or replace function public.erp_session_division() returns text
language sql stable security definer set search_path = public, extensions as $$
  select s.division from public.sessions s where s.token_hash = public.erp_current_token_hash()
$$;

create or replace function public.erp_session_info() returns json
language sql stable security definer set search_path = public, extensions as $$
  select json_build_object('department', s.department_id, 'division', s.division,
                           'display_name', d.display_name, 'username', d.username)
  from public.sessions s join public.departments d on d.id = s.department_id
  where s.token_hash = public.erp_current_token_hash()
$$;

create or replace function public.erp_setup_needed() returns boolean
language sql stable security definer set search_path = public as $$
  select not exists (select 1 from public.departments)
$$;

-- First start only: create the department accounts.
create or replace function public.erp_setup(
  p_crops_user text, p_crops_pass text,
  p_app_user text, p_app_pass text,
  p_owner_user text default null, p_owner_pass text default null
) returns json
language plpgsql security definer set search_path = public, extensions as $$
begin
  lock table public.departments in exclusive mode;
  if exists (select 1 from public.departments) then
    return json_build_object('error', 'configured');
  end if;
  if coalesce(trim(p_crops_user), '') = '' or coalesce(trim(p_app_user), '') = '' then
    return json_build_object('error', 'username');
  end if;
  if lower(trim(p_crops_user)) = lower(trim(p_app_user))
     or lower(trim(coalesce(p_owner_user, ''))) in (lower(trim(p_crops_user)), lower(trim(p_app_user))) then
    return json_build_object('error', 'duplicate');
  end if;
  if coalesce(length(p_crops_pass), 0) < 6 or coalesce(length(p_app_pass), 0) < 6
     or (coalesce(trim(p_owner_user), '') <> '' and coalesce(length(p_owner_pass), 0) < 6) then
    return json_build_object('error', 'short');
  end if;
  insert into public.departments (id, username, password_hash, display_name, division) values
    ('crops', trim(p_crops_user), extensions.crypt(p_crops_pass, extensions.gen_salt('bf', 8)), 'التجارة', 'crops'),
    ('appliances', trim(p_app_user), extensions.crypt(p_app_pass, extensions.gen_salt('bf', 8)), 'المعرض', 'appliances');
  if coalesce(trim(p_owner_user), '') <> '' then
    insert into public.departments (id, username, password_hash, display_name, division) values
      ('owner', trim(p_owner_user), extensions.crypt(p_owner_pass, extensions.gen_salt('bf', 8)), 'الإدارة', 'all');
  end if;
  return json_build_object('ok', true);
end $$;

-- Errors are returned (not raised) so the failed-attempt counter is saved.
create or replace function public.erp_login(
  p_username text, p_password text, p_device uuid, p_device_name text, p_person text
) returns json
language plpgsql security definer set search_path = public, extensions as $$
declare
  v_user text := lower(trim(coalesce(p_username, '')));
  d public.departments;
  a public.login_attempts;
  v_token text;
  v_code integer;
begin
  select * into a from public.login_attempts where username = v_user;
  if a.locked_until is not null and a.locked_until > now() then
    return json_build_object('error', 'locked',
      'seconds', ceil(extract(epoch from (a.locked_until - now())))::int);
  end if;
  select * into d from public.departments where lower(username) = v_user;
  if d.id is null or d.password_hash <> extensions.crypt(coalesce(p_password, ''), d.password_hash) then
    insert into public.login_attempts as la (username, failures) values (v_user, 1)
    on conflict (username) do update set
      failures = case when la.locked_until is not null then 1 else la.failures + 1 end,
      locked_until = case when la.locked_until is null and la.failures + 1 >= 5
                          then now() + interval '5 minutes' end;
    return json_build_object('error', 'invalid');
  end if;
  delete from public.login_attempts where username = v_user;
  v_token := encode(extensions.gen_random_bytes(32), 'hex');
  insert into public.sessions (token_hash, department_id, division, device_id, person)
  values (public.erp_token_hash(v_token), d.id, d.division, p_device, nullif(trim(p_person), ''));
  if p_device is not null then
    update public.devices set last_seen = now(), name = coalesce(p_device_name, name)
      where id = p_device returning code into v_code;
    if v_code is null then
      insert into public.devices (id, name) values (p_device, p_device_name)
      on conflict (id) do update set last_seen = now()
      returning code into v_code;
    end if;
  end if;
  return json_build_object('token', v_token, 'department', d.id, 'division', d.division,
                           'display_name', d.display_name, 'device_code', v_code);
end $$;

create or replace function public.erp_logout() returns void
language sql security definer set search_path = public, extensions as $$
  delete from public.sessions where token_hash = public.erp_current_token_hash()
$$;

-- Departments the current session may manage (the owner manages all).
create or replace function public.erp_departments() returns json
language sql stable security definer set search_path = public, extensions as $$
  select coalesce(json_agg(json_build_object('id', d.id, 'username', d.username,
                                             'display_name', d.display_name) order by d.id), '[]'::json)
  from public.departments d
  where public.erp_session_division() = 'all' or d.division = public.erp_session_division()
$$;

-- Change a department's username / password. Everybody else signed in to
-- that department has to sign in again.
create or replace function public.erp_change_password(
  p_department text, p_old text, p_new text, p_new_username text default null
) returns json
language plpgsql security definer set search_path = public, extensions as $$
declare
  v_div text := public.erp_session_division();
  v_hash text := public.erp_current_token_hash();
  d public.departments;
begin
  if v_div is null then return json_build_object('error', 'session'); end if;
  select * into d from public.departments where id = p_department;
  if d.id is null then return json_build_object('error', 'department'); end if;
  if v_div <> 'all' and v_div <> d.division then return json_build_object('error', 'forbidden'); end if;
  if v_div <> 'all' and d.password_hash <> extensions.crypt(coalesce(p_old, ''), d.password_hash) then
    return json_build_object('error', 'old_password');
  end if;
  if coalesce(length(p_new), 0) < 6 then return json_build_object('error', 'short'); end if;
  if coalesce(trim(p_new_username), '') <> '' and exists (
       select 1 from public.departments where lower(username) = lower(trim(p_new_username)) and id <> d.id) then
    return json_build_object('error', 'duplicate');
  end if;
  update public.departments set
    password_hash = extensions.crypt(p_new, extensions.gen_salt('bf', 8)),
    username = coalesce(nullif(trim(p_new_username), ''), username),
    updated_at = now()
  where id = d.id;
  delete from public.sessions where department_id = d.id and token_hash <> v_hash;
  return json_build_object('ok', true);
end $$;

create or replace function public.server_now() returns timestamptz
language sql volatile as $$ select clock_timestamp() $$;

-- Changes every time supabase/reset_data.sql wipes the data; phones compare it
-- before uploading, so an old copy is never sent back to a wiped server.
create table if not exists public.erp_state (
  id integer primary key default 1 check (id = 1),
  reset_id text not null default gen_random_uuid()::text,
  reset_at timestamptz not null default now()
);
insert into public.erp_state (id) values (1) on conflict (id) do nothing;
alter table public.erp_state enable row level security;
revoke all on public.erp_state from anon, authenticated;

create or replace function public.erp_reset_id() returns text
language sql stable security definer set search_path = public as $$
  select reset_id from public.erp_state where id = 1
$$;

grant execute on function public.erp_token_hash(text) to anon, authenticated;
grant execute on function public.erp_current_token_hash() to anon, authenticated;
grant execute on function public.erp_session_division() to anon, authenticated;
grant execute on function public.erp_session_info() to anon, authenticated;
grant execute on function public.erp_setup_needed() to anon, authenticated;
grant execute on function public.erp_setup(text, text, text, text, text, text) to anon, authenticated;
grant execute on function public.erp_login(text, text, uuid, text, text) to anon, authenticated;
grant execute on function public.erp_logout() to anon, authenticated;
grant execute on function public.erp_departments() to anon, authenticated;
grant execute on function public.erp_change_password(text, text, text, text) to anon, authenticated;
grant execute on function public.server_now() to anon, authenticated;
grant execute on function public.erp_reset_id() to anon, authenticated;
''';

const footer = r'''
-- Version 1 functions, no longer referenced by any policy.
drop function if exists public.register_device(uuid, text);
drop function if exists public.is_active_member();
drop function if exists public.is_admin();
''';

/// supabase/reset_data.sql: wipes the trial data, keeps tables, functions,
/// policies and (unless asked) the department logins.
String resetSql() {
  final tables = [for (final t in syncedTables) 'public.${t.name}'].join(',\n  ');
  return '''
-- ============================================================================
-- مسح كل البيانات التجريبية من السيرفر
--
-- بيمسح: العملاء والفلاحين والتجار، الأصناف، الفواتير، المحاصيل والتوريدات،
-- الخزن والفلوس، المخازن، التذكرة، إعدادات المؤسسة، والموبايلات المتسجلة،
-- وحسابات الإيميل بتاعة النسخة الأولى.
-- مش بيمسح: أسماء المستخدمين وكلمات المرور بتاعة المعرض والتجارة والإدارة
-- (شوف آخر الملف لو عايز تمسحهم كمان).
--
-- بعد ما تشغّله: كل موبايل هيسجل دخول تاني، وأول ما يتصل بالسيرفر هيمسح
-- البيانات القديمة اللي عليه لوحده. المحاصيل الأساسية والخزنة والمخزن
-- الرئيسي بيتعملوا تاني أوتوماتيك.
--
-- الطريقة: Supabase ← SQL Editor ← New query، الصق الملف كله ودوس Run.
-- شغّل ملف schema.sql الجديد الأول لو لسه ماشغلتوش.
-- ============================================================================

do \$\$
begin
  if to_regclass('public.erp_state') is null then
    raise exception 'شغّل ملف supabase/schema.sql الجديد الأول، وبعدين الملف ده';
  end if;
end \$\$;

begin;

-- 1) كل البيانات في القسمين
truncate table
  $tables;

-- 2) الدخول والموبايلات: كل موبايل يسجل دخول من جديد
truncate table public.sessions, public.login_attempts, public.devices;

-- 3) نقول للموبايلات إن البيانات اتمسحت
update public.erp_state set reset_id = gen_random_uuid()::text, reset_at = now() where id = 1;

-- 4) حسابات الإيميل بتاعة النسخة الأولى (الأبلكيشن مابقاش يستخدمها)
do \$\$
begin
  if to_regclass('auth.users') is not null then
    delete from auth.users;
  end if;
end \$\$;

commit;

-- ----------------------------------------------------------------------------
-- (اختياري) لو عايز كمان تمسح أسماء المستخدمين وكلمات المرور وتعملهم من الأول
-- من الأبلكيشن: شيل علامتين الشرطة "--" من أول السطر اللي تحت وشغّله لوحده.
-- truncate table public.departments;
''';
}

void main() {
  final out = StringBuffer(header);
  out.writeln(accessSql);
  for (final t in syncedTables) {
    out.writeln(tableSql(t));
  }
  out.writeln(footer);
  final file = File('supabase/schema.sql');
  file.parent.createSync(recursive: true);
  file.writeAsStringSync(out.toString().replaceAll('\r\n', '\n'));
  stdout.writeln('wrote ${file.path} (${out.length} chars)');
  final reset = File('supabase/reset_data.sql');
  reset.writeAsStringSync(resetSql());
  stdout.writeln('wrote ${reset.path}');
}
